version: '3.7'

services:
  vue: 
    build: ./frontend
    container_name: VUE_FRONT
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/app
  
  express:
    build: ./backend
    container_name: EXPRESS_API
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app